language: c

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository -y ppa:myriadrf/drivers;
      sudo add-apt-repository -y ppa:bladerf/bladerf;
      sudo apt-get -q update;
      sudo apt-get -y install build-essential debhelper dh-systemd fakeroot pkg-config libncurses-dev librtlsdr-dev libhackrf-dev liblimesuite-dev libbladerf-dev;
    fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew install librtlsdr;
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      dpkg-buildpackage -b -us -uc;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      make;
      make test;
    fi
